# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTest1():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_test1(self):
    self.driver.get("https://formy-project.herokuapp.com/form")
    self.driver.set_window_size(1107, 688)
    self.driver.find_element(By.ID, "first-name").click()
    self.driver.find_element(By.ID, "first-name").send_keys("Alexandru")
    self.driver.find_element(By.ID, "last-name").click()
    self.driver.find_element(By.ID, "first-name").click()
    self.driver.find_element(By.ID, "radio-button-1").click()
    self.driver.find_element(By.ID, "checkbox-1").click()
    self.driver.find_element(By.ID, "select-menu").click()
    dropdown = self.driver.find_element(By.ID, "select-menu")
    dropdown.find_element(By.XPATH, "//option[. = '10+']").click()
    self.driver.find_element(By.ID, "datepicker").click()
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(3) > .day:nth-child(4)").click()
    self.driver.find_element(By.LINK_TEXT, "Submit").click()
  
